In [4]:
source_csv = '../../en.openfoodfacts.org.products.csv'
source_parquet = '../../food.parquet'

print('TP 1:')
print()

import platform
print(f"Python version : {platform.python_version()}")

import pandas as pd
import numpy as np
import datetime as dt

print(f"Pandas version : {pd.__version__}")
print(f"Numpy version : {np.__version__}")

TP 1:

Python version : 3.12.10
Pandas version : 3.0.5
Numpy version : 2.5.2

In [5]:
# Outils

from pathlib import Path
import humanize

# Time
import time

class ExecutionTime:
    _start = 0

    def __init__(self):
        self._start = 0

    def start(self):
        self._start = time.time()

    def end(self, text = ""):
        time_exec = time.time() - self._start
        print(f"Execution time {text}: {humanize.precisedelta(time_exec, minimum_unit="microseconds")}")
        print('-----------------------\n')

t = ExecutionTime()

In [6]:
print('CSV:')
print()

t.start()
file_csv = Path(source_csv)
print(f"CSV size: {humanize.naturalsize(file_csv.stat().st_size)}")
print(f"Last metadata change: {dt.datetime.fromtimestamp((file_csv.stat().st_ctime)).strftime("%Y-%m-%d %H:%M:%S")}")
t.end("(pathlib.stat())")

print('CSV SAMPLE DATA')

t.start()

df_csv = pd.read_csv(
    source_csv,
    skipinitialspace=True,
    sep="\t",
    nrows=3,
)

print(f"Dimensions : {df_csv.shape}")
print(f"→ {df_csv.shape[0]} lines, {df_csv.shape[1]} columns\n")

print('Columns name:')
columns_name = list(df_csv)
display(list(df_csv))

print('Sample data:')
transposed = np.transpose(df_csv)
with pd.option_context('display.max_rows', None):
    display(transposed)

t.end()

CSV:

CSV size: 13.0 GB
Last metadata change: 2026-08-18 08:50:54
Execution time (pathlib.stat()): 1 millisecond and 448 microseconds
-----------------------

CSV SAMPLE DATA
Dimensions : (3, 211)
→ 3 lines, 211 columns

Columns name:

['code',
 'url',
 'creator',
 'created_t',
 'created_datetime',
 'last_modified_t',
 'last_modified_datetime',
 'last_modified_by',
 'last_updated_t',
 'last_updated_datetime',
 'product_name',
 'abbreviated_product_name',
 'generic_name',
 'quantity',
 'packaging',
 'packaging_tags',
 'packaging_en',
 'packaging_text',
 'brands',
 'brands_tags',
 'brands_en',
 'categories',
 'categories_tags',
 'categories_en',
 'origins',
 'origins_tags',
 'origins_en',
 'manufacturing_places',
 'manufacturing_places_tags',
 'labels',
 'labels_tags',
 'labels_en',
 'emb_codes',
 'emb_codes_tags',
 'first_packaging_code_geo',
 'cities',
 'cities_tags',
 'purchase_places',
 'stores',
 'countries',
 'countries_tags',
 'countries_en',
 'ingredients_text',
 'ingredients_tags',
 'ingredients_analysis_tags',
 'allergens',
 'allergens_en',
 'traces',
 'traces_tags',
 'traces_en',
 'serving_size',
 'serving_quantity',
 'no_nutrition_data',
 'additives_n',
 'additives',
 'additives_tags',
 'additives_en',
 'nutriscore_score',
 'nutriscore_grade',
 'nova_group',
 'pnns_groups_1',
 'pnns_groups_2',
 'food_groups',
 'food_groups_tags',
 'food_groups_en',
 'states',
 'states_tags',
 'states_en',
 'brand_owner',
 'environmental_score_score',
 'environmental_score_grade',
 'nutrient_levels_tags',
 'product_quantity',
 'owner',
 'data_quality_errors_tags',
 'unique_scans_n',
 'popularity_tags',
 'completeness',
 'last_image_t',
 'last_image_datetime',
 'main_category',
 'main_category_en',
 'image_url',
 'image_small_url',
 'image_ingredients_url',
 'image_ingredients_small_url',
 'image_nutrition_url',
 'image_nutrition_small_url',
 'energy-kj_100g',
 'energy-kcal_100g',
 'energy_100g',
 'energy-from-fat_100g',
 'fat_100g',
 'saturated-fat_100g',
 'butyric-acid_100g',
 'caproic-acid_100g',
 'caprylic-acid_100g',
 'capric-acid_100g',
 'lauric-acid_100g',
 'myristic-acid_100g',
 'palmitic-acid_100g',
 'stearic-acid_100g',
 'arachidic-acid_100g',
 'behenic-acid_100g',
 'lignoceric-acid_100g',
 'cerotic-acid_100g',
 'montanic-acid_100g',
 'melissic-acid_100g',
 'unsaturated-fat_100g',
 'monounsaturated-fat_100g',
 'omega-9-fat_100g',
 'polyunsaturated-fat_100g',
 'omega-3-fat_100g',
 'omega-6-fat_100g',
 'alpha-linolenic-acid_100g',
 'eicosapentaenoic-acid_100g',
 'docosahexaenoic-acid_100g',
 'linoleic-acid_100g',
 'arachidonic-acid_100g',
 'gamma-linolenic-acid_100g',
 'dihomo-gamma-linolenic-acid_100g',
 'oleic-acid_100g',
 'elaidic-acid_100g',
 'gondoic-acid_100g',
 'mead-acid_100g',
 'erucic-acid_100g',
 'nervonic-acid_100g',
 'trans-fat_100g',
 'cholesterol_100g',
 'carbohydrates_100g',
 'sugars_100g',
 'added-sugars_100g',
 'sucrose_100g',
 'glucose_100g',
 'fructose_100g',
 'galactose_100g',
 'lactose_100g',
 'maltose_100g',
 'maltodextrins_100g',
 'psicose_100g',
 'starch_100g',
 'polyols_100g',
 'erythritol_100g',
 'isomalt_100g',
 'maltitol_100g',
 'sorbitol_100g',
 'fiber_100g',
 'soluble-fiber_100g',
 'polydextrose_100g',
 'insoluble-fiber_100g',
 'proteins_100g',
 'casein_100g',
 'serum-proteins_100g',
 'nucleotides_100g',
 'salt_100g',
 'added-salt_100g',
 'sodium_100g',
 'alcohol_100g',
 'vitamin-a_100g',
 'beta-carotene_100g',
 'vitamin-d_100g',
 'vitamin-e_100g',
 'vitamin-k_100g',
 'vitamin-c_100g',
 'vitamin-b1_100g',
 'vitamin-b2_100g',
 'vitamin-pp_100g',
 'vitamin-b6_100g',
 'vitamin-b9_100g',
 'folates_100g',
 'vitamin-b12_100g',
 'biotin_100g',
 'pantothenic-acid_100g',
 'silica_100g',
 'bicarbonate_100g',
 'potassium_100g',
 'chloride_100g',
 'calcium_100g',
 'phosphorus_100g',
 'iron_100g',
 'magnesium_100g',
 'zinc_100g',
 'copper_100g',
 'manganese_100g',
 'fluoride_100g',
 'selenium_100g',
 'chromium_100g',
 'molybdenum_100g',
 'iodine_100g',
 'caffeine_100g',
 'taurine_100g',
 'methylsulfonylmethane_100g',
 'hydroxymethylbutyrate_100g',
 'ph_100g',
 'fruits-vegetables-legumes_100g',
 'collagen-meat-protein-ratio_100g',
 'cocoa_100g',
 'chlorophyl_100g',
 'carbon-footprint_100g',
 'glycemic-index_100g',
 'water-hardness_100g',
 'choline_100g',
 'phylloquinone_100g',
 'beta-glucan_100g',
 'inositol_100g',
 'carnitine_100g',
 'sulphate_100g',
 'nitrate_100g',
 'acidity_100g',
 'carbohydrates-total_100g',
 'water_100g']

Sample data:

,0,1,2
code,54,63,114
url,http://world-en.openfoodfacts.org/product/0000...,http://world-en.openfoodfacts.org/product/0000...,http://world-en.openfoodfacts.org/product/0000...
creator,kiliweb,kiliweb,kiliweb
created_t,1582569031,1673620307,1580066482
created_datetime,2020-02-24T18:30:31Z,2023-01-13T14:31:47Z,2020-01-26T19:21:22Z
last_modified_t,1733085204,1750061386,1751035658
last_modified_datetime,2024-12-01T20:33:24Z,2025-06-16T08:09:46Z,2025-06-27T14:47:38Z
last_modified_by,NaN,bodysupport,teolemon
last_updated_t,1740205422,1750061386,1751035658
last_updated_datetime,2025-02-22T06:23:42Z,2025-06-16T08:09:46Z,2025-06-27T14:47:38Z
product_name,Limonade artisanale a la rose,M&amp;M white,Chocolate n3
abbreviated_product_name,NaN,NaN,NaN
generic_name,NaN,NaN,NaN
quantity,NaN,80 gram,80 g
packaging,NaN,NaN,NaN
packaging_tags,NaN,NaN,NaN
packaging_en,NaN,NaN,NaN
packaging_text,NaN,NaN,NaN
brands,NaN,Fitpiggy,Jeff de Bruges
brands_tags,NaN,xx:fitpiggy,xx:jeff-de-bruges
brands_en,NaN,fitpiggy,jeff-de-bruges
categories,NaN,NaN,NaN
categories_tags,NaN,NaN,NaN
categories_en,NaN,NaN,NaN
origins,NaN,NaN,NaN
origins_tags,NaN,NaN,NaN
origins_en,NaN,NaN,NaN
manufacturing_places,NaN,NaN,NaN
manufacturing_places_tags,NaN,NaN,NaN
labels,NaN,NaN,"Green Dot,Made in France"
labels_tags,NaN,NaN,"en:green-dot,en:made-in-france"
labels_en,NaN,NaN,"Green Dot,Made in France"
emb_codes,NaN,NaN,NaN
emb_codes_tags,NaN,NaN,NaN
first_packaging_code_geo,NaN,NaN,NaN
cities,NaN,NaN,NaN
cities_tags,NaN,NaN,NaN
purchase_places,NaN,NaN,NaN
stores,NaN,NaN,NaN
countries,en:fr,en:fr,France
countries_tags,en:france,en:france,en:france
countries_en,France,France,France
ingredients_text,NaN,"Weizenmehl, Rapsöl, Speisesalz, 1,7% Meersalz,...",NaN
ingredients_tags,NaN,"en:weizenmehl,en:rapsol,en:speisesalz,en:meers...",NaN
ingredients_analysis_tags,NaN,"en:palm-oil-content-unknown,en:vegan-status-un...",NaN
allergens,NaN,NaN,NaN
allergens_en,NaN,NaN,NaN
traces,NaN,NaN,NaN
traces_tags,NaN,NaN,NaN
traces_en,NaN,NaN,NaN
serving_size,NaN,80 gram,NaN
serving_quantity,NaN,80.0,NaN
no_nutrition_data,NaN,NaN,NaN
additives_n,NaN,0.0,NaN
additives,NaN,NaN,NaN
additives_tags,NaN,NaN,NaN
additives_en,NaN,NaN,NaN
nutriscore_score,NaN,NaN,NaN
nutriscore_grade,unknown,unknown,unknown
nova_group,NaN,NaN,NaN
pnns_groups_1,unknown,unknown,unknown
pnns_groups_2,unknown,unknown,unknown
food_groups,NaN,NaN,NaN
food_groups_tags,NaN,NaN,NaN
food_groups_en,NaN,NaN,NaN
states,"en:to-be-completed, en:nutrition-facts-to-be-c...","en:to-be-completed, en:nutrition-facts-complet...","en:to-be-completed, en:nutrition-facts-complet..."
states_tags,"en:to-be-completed,en:nutrition-facts-to-be-co...","en:to-be-completed,en:nutrition-facts-complete...","en:to-be-completed,en:nutrition-facts-complete..."
states_en,"To be completed,Nutrition facts to be complete...","To be completed,Nutrition facts completed,Ingr...","To be completed,Nutrition facts completed,Ingr..."
brand_owner,NaN,NaN,NaN
environmental_score_score,NaN,NaN,NaN
environmental_score_grade,unknown,unknown,unknown
nutrient_levels_tags,NaN,NaN,NaN
product_quantity,NaN,80.0,80.0
owner,NaN,NaN,NaN
data_quality_errors_tags,NaN,NaN,NaN
unique_scans_n,NaN,1.0,1.0
popularity_tags,NaN,"top-75-percent-scans-2024,top-80-percent-scans...","bottom-25-percent-scans-2022,bottom-20-percent..."
completeness,0.1625,0.6625,0.475
last_image_t,1733085204,1746257766,1737247860
last_image_datetime,2024-12-01T20:33:24Z,2025-05-03T07:36:06Z,2025-01-19T00:51:00Z
main_category,NaN,NaN,NaN
main_category_en,NaN,NaN,NaN
image_url,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...
image_small_url,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...,https://images.openfoodfacts.org/images/produc...
image_ingredients_url,NaN,https://images.openfoodfacts.org/images/produc...,NaN
image_ingredients_small_url,NaN,https://images.openfoodfacts.org/images/produc...,NaN
image_nutrition_url,NaN,NaN,https://images.openfoodfacts.org/images/produc...
image_nutrition_small_url,NaN,NaN,https://images.openfoodfacts.org/images/produc...
energy-kj_100g,NaN,NaN,NaN
energy-kcal_100g,NaN,NaN,NaN
energy_100g,NaN,NaN,NaN
energy-from-fat_100g,NaN,NaN,NaN
fat_100g,NaN,NaN,NaN
saturated-fat_100g,NaN,NaN,NaN
butyric-acid_100g,NaN,NaN,NaN
caproic-acid_100g,NaN,NaN,NaN
caprylic-acid_100g,NaN,NaN,NaN
capric-acid_100g,NaN,NaN,NaN
lauric-acid_100g,NaN,NaN,NaN
myristic-acid_100g,NaN,NaN,NaN
palmitic-acid_100g,NaN,NaN,NaN
stearic-acid_100g,NaN,NaN,NaN
arachidic-acid_100g,NaN,NaN,NaN
behenic-acid_100g,NaN,NaN,NaN
lignoceric-acid_100g,NaN,NaN,NaN
cerotic-acid_100g,NaN,NaN,NaN
montanic-acid_100g,NaN,NaN,NaN
melissic-acid_100g,NaN,NaN,NaN
unsaturated-fat_100g,NaN,NaN,NaN
monounsaturated-fat_100g,NaN,NaN,NaN
omega-9-fat_100g,NaN,NaN,NaN
polyunsaturated-fat_100g,NaN,NaN,NaN
omega-3-fat_100g,NaN,NaN,NaN
omega-6-fat_100g,NaN,NaN,NaN
alpha-linolenic-acid_100g,NaN,NaN,NaN
eicosapentaenoic-acid_100g,NaN,NaN,NaN
docosahexaenoic-acid_100g,NaN,NaN,NaN
linoleic-acid_100g,NaN,NaN,NaN
arachidonic-acid_100g,NaN,NaN,NaN
gamma-linolenic-acid_100g,NaN,NaN,NaN
dihomo-gamma-linolenic-acid_100g,NaN,NaN,NaN
oleic-acid_100g,NaN,NaN,NaN
elaidic-acid_100g,NaN,NaN,NaN
gondoic-acid_100g,NaN,NaN,NaN
mead-acid_100g,NaN,NaN,NaN
erucic-acid_100g,NaN,NaN,NaN
nervonic-acid_100g,NaN,NaN,NaN
trans-fat_100g,NaN,NaN,NaN
cholesterol_100g,NaN,NaN,NaN
carbohydrates_100g,NaN,NaN,NaN
sugars_100g,NaN,NaN,NaN
added-sugars_100g,NaN,NaN,NaN
sucrose_100g,NaN,NaN,NaN
glucose_100g,NaN,NaN,NaN
fructose_100g,NaN,NaN,NaN
galactose_100g,NaN,NaN,NaN
lactose_100g,NaN,NaN,NaN
maltose_100g,NaN,NaN,NaN
maltodextrins_100g,NaN,NaN,NaN
psicose_100g,NaN,NaN,NaN
starch_100g,NaN,NaN,NaN
polyols_100g,NaN,NaN,NaN
erythritol_100g,NaN,NaN,NaN
isomalt_100g,NaN,NaN,NaN
maltitol_100g,NaN,NaN,NaN
sorbitol_100g,NaN,NaN,NaN
fiber_100g,NaN,NaN,NaN
soluble-fiber_100g,NaN,NaN,NaN
polydextrose_100g,NaN,NaN,NaN
insoluble-fiber_100g,NaN,NaN,NaN
proteins_100g,NaN,NaN,NaN
casein_100g,NaN,NaN,NaN
serum-proteins_100g,NaN,NaN,NaN
nucleotides_100g,NaN,NaN,NaN
salt_100g,NaN,NaN,NaN
added-salt_100g,NaN,NaN,NaN
sodium_100g,NaN,NaN,NaN
alcohol_100g,NaN,NaN,NaN
vitamin-a_100g,NaN,NaN,NaN
beta-carotene_100g,NaN,NaN,NaN
vitamin-d_100g,NaN,NaN,NaN
vitamin-e_100g,NaN,NaN,NaN
vitamin-k_100g,NaN,NaN,NaN
vitamin-c_100g,NaN,NaN,NaN
vitamin-b1_100g,NaN,NaN,NaN
vitamin-b2_100g,NaN,NaN,NaN
vitamin-pp_100g,NaN,NaN,NaN
vitamin-b6_100g,NaN,NaN,NaN
vitamin-b9_100g,NaN,NaN,NaN
folates_100g,NaN,NaN,NaN
vitamin-b12_100g,NaN,NaN,NaN
biotin_100g,NaN,NaN,NaN
pantothenic-acid_100g,NaN,NaN,NaN
silica_100g,NaN,NaN,NaN
bicarbonate_100g,NaN,NaN,NaN
potassium_100g,NaN,NaN,NaN
chloride_100g,NaN,NaN,NaN
calcium_100g,NaN,NaN,NaN
phosphorus_100g,NaN,NaN,NaN
iron_100g,NaN,NaN,NaN
magnesium_100g,NaN,NaN,NaN
zinc_100g,NaN,NaN,NaN
copper_100g,NaN,NaN,NaN
manganese_100g,NaN,NaN,NaN
fluoride_100g,NaN,NaN,NaN
selenium_100g,NaN,NaN,NaN
chromium_100g,NaN,NaN,NaN
molybdenum_100g,NaN,NaN,NaN
iodine_100g,NaN,NaN,NaN
caffeine_100g,NaN,NaN,NaN
taurine_100g,NaN,NaN,NaN
methylsulfonylmethane_100g,NaN,NaN,NaN
hydroxymethylbutyrate_100g,NaN,NaN,NaN
ph_100g,NaN,NaN,NaN
fruits-vegetables-legumes_100g,NaN,NaN,NaN
collagen-meat-protein-ratio_100g,NaN,NaN,NaN
cocoa_100g,NaN,NaN,NaN
chlorophyl_100g,NaN,NaN,NaN
carbon-footprint_100g,NaN,NaN,NaN
glycemic-index_100g,NaN,NaN,NaN
water-hardness_100g,NaN,NaN,NaN
choline_100g,NaN,NaN,NaN
phylloquinone_100g,NaN,NaN,NaN
beta-glucan_100g,NaN,NaN,NaN
inositol_100g,NaN,NaN,NaN
carnitine_100g,NaN,NaN,NaN
sulphate_100g,NaN,NaN,NaN
nitrate_100g,NaN,NaN,NaN
acidity_100g,NaN,NaN,NaN
carbohydrates-total_100g,NaN,NaN,NaN
water_100g,NaN,NaN,NaN

Execution time : 52 milliseconds and 309 microseconds
-----------------------

In [7]:
print('CSV FULL DATA (filtrage colonnes utiles pour analyse)')

check_duplicated = ["code"]

use_cols = check_duplicated + [
    "product_name", "brands",
    "countries",
    "energy_100g", "sugars_100g", "salt_100g",
    "nutriscore_score"
]

t.start()

chunk_iterator_csv = pd.read_csv(
    source_csv,
    memory_map=True,
    skipinitialspace=True,
    sep="\t",
    chunksize=10000,
    low_memory = False,
    on_bad_lines="skip",
    usecols=use_cols
)

full_data_csv = []

for chunk in chunk_iterator_csv:
    full_data_csv.append(chunk)

df_full_csv = pd.concat(full_data_csv, ignore_index=True)

t.end('Load data')

CSV FULL DATA (filtrage colonnes utiles pour analyse)
Execution time Load data: 1 minute, 30 seconds, 544 milliseconds and 342 microseconds
-----------------------

In [8]:
print('Analyse:')

t.start()

display(df_full_csv.info())

print(f"Dimensions: {df_full_csv.shape}")
print(f"→ {df_full_csv.shape[0]} lines, {df_full_csv.shape[1]} columns")
print()

print(f"Duplication: {check_duplicated}:")
print(df_full_csv.duplicated(subset=check_duplicated).value_counts())
print()

print("Valeurs non-renseignées | Taux de remplissage par colonnes:")
missing = pd.DataFrame({
    'total_manquants': df_full_csv.isna().sum(),
    '%': 100 - (df_full_csv.isna().sum() / len(df_full_csv) * 100).round(2)
})
print(missing)
print()

# Voir https://static.openfoodfacts.org/data/data-fields.txt
print("Produits vendu en France ([countries].str.contains(fr)):")
print(df_full_csv[df_full_csv["countries"].str.contains("fr")].shape[0])
print()

print("Top 10 marques: ")
print(df_full_csv.groupby(["brands"]).size().sort_values(ascending=False)[0:10])
print()

print("Quelle part de Nutri-Score renseigné ?")
print(f"Total: {df_full_csv.shape[0]}")
print(f"Manquant: {df_full_csv["nutriscore_score"].isna().sum()}")
print(f"Nutri-Score non-renseignés: {(df_full_csv["nutriscore_score"].isna().sum() / len(df_full_csv) * 100).round(2)}%")

t.end()

Analyse:
<class 'pandas.DataFrame'>
RangeIndex: 4532767 entries, 0 to 4532766
Data columns (total 8 columns):
 #   Column            Dtype
---  ------            -----
 0   code              object
 1   product_name      str
 2   brands            str
 3   countries         str
 4   nutriscore_score  object
 5   energy_100g       object
 6   sugars_100g       float64
 7   salt_100g         float64
dtypes: float64(2), object(3), str(3)
memory usage: 434.5+ MB

None

Dimensions: (4532767, 8)
→ 4532767 lines, 8 columns

Duplication: ['code']:
False    4532701
True          66
Name: count, dtype: int64

Valeurs non-renseignées | Taux de remplissage par colonnes:
                  total_manquants       %
code                            0  100.00
product_name               335833   92.59
brands                    1682789   62.88
countries                   22828   99.50
nutriscore_score          3157914   30.33
energy_100g               2296811   49.33
sugars_100g               2388528   47.31
salt_100g                 2580977   43.06

Produits vendu en France ([countries].str.contains(fr)):
590241

Top 10 marques:
brands
Carrefour    25641
Auchan       18107
Coop         14067
Lidl         13804
U            12286
BonÀrea      12193
Aldi         11683
Hacendado    10490
Tesco        10282
Delhaize      9741
dtype: int64

Quelle part de Nutri-Score renseigné ?
Total: 4532767
Manquant: 3157914
Nutri-Score non-renseignés: 69.67%
Execution time : 3 seconds, 32 milliseconds and 324 microseconds
-----------------------

In [9]:
print('PARQUET:')
print()

import pyarrow as pa
import duckdb as db

print(f"Pyarrow version : {pa.__version__}")
print(f"Duckdb version : {db.__version__}")

PARQUET:

Pyarrow version : 25.0.1
Duckdb version : 1.5.5

In [10]:
file_parquet = Path(source_parquet)

print()
print(f"Parquet size: {humanize.naturalsize(file_parquet.stat().st_size)}")
print(f"Last metadata change: {dt.datetime.fromtimestamp((file_parquet.stat().st_ctime)).strftime("%Y-%m-%d %H:%M:%S")}")
t.end("(pathlib.stat())")

Parquet size: 7.7 GB
Last metadata change: 2026-07-29 14:51:32
Execution time (pathlib.stat()): 3 seconds, 239 milliseconds and 598 microseconds
-----------------------

In [11]:
import pyarrow.parquet as pq

schema = pq.read_schema(source_parquet)

print('Columns name:')

schema_columns_name = []

for field in schema:
    schema_columns_name.append(field.name)
    print(field.name, field.type)

Columns name:
additives_n int32
additives_tags list<element: string>
allergens_tags list<element: string>
brands_tags list<element: string>
brands string
categories string
categories_tags list<element: string>
categories_properties struct<ciqual_food_code: int32, agribalyse_food_code: int32, agribalyse_proxy_food_code: int32>
checkers_tags list<element: string>
ciqual_food_name_tags list<element: string>
cities_tags list<element: string>
code string
compared_to_category string
complete int32
completeness float
correctors_tags list<element: string>
countries_tags list<element: string>
created_t int64
creator string
data_quality_errors_tags list<element: string>
data_quality_info_tags list<element: string>
data_quality_warnings_tags list<element: string>
data_sources_tags list<element: string>
environmental_score_data string
environmental_score_grade string
environmental_score_score int32
environmental_score_tags list<element: string>
editors list<element: string>
emb_codes_tags list<element: string>
emb_codes string
entry_dates_tags list<element: string>
food_groups_tags list<element: string>
generic_name list<element: struct<lang: string, text: string>>
images list<element: struct<key: string, imgid: int32, rev: int32, sizes: struct<100: struct<h: int32, w: int32>, 200: struct<h: int32, w: int32>, 400: struct<h: int32, w: int32>, full: struct<h: int32, w: int32>>, uploaded_t: int64, uploader: string>>
informers_tags list<element: string>
ingredients_analysis_tags list<element: string>
ingredients_from_palm_oil_n int32
ingredients_n int32
ingredients_original_tags list<element: string>
ingredients_percent_analysis int32
ingredients_tags list<element: string>
ingredients_text list<element: struct<lang: string, text: string>>
ingredients_with_specified_percent_n int32
ingredients_with_unspecified_percent_n int32
ingredients_without_ciqual_codes_n int32
ingredients_without_ciqual_codes list<element: string>
ingredients string
known_ingredients_n int32
labels_tags list<element: string>
labels string
lang string
languages_tags list<element: string>
last_edit_dates_tags list<element: string>
last_editor string
last_image_t int64
last_modified_by string
last_modified_t int64
last_updated_t int64
link string
main_countries_tags list<element: string>
manufacturing_places_tags list<element: string>
manufacturing_places string
max_imgid int32
minerals_tags list<element: string>
misc_tags list<element: string>
new_additives_n int32
no_nutrition_data bool
nova_group int32
nova_groups_tags list<element: string>
nova_groups string
nucleotides_tags list<element: string>
nutrient_levels_tags list<element: string>
nutriments list<element: struct<name: string, value: float, 100g: float, serving: float, unit: string, prepared_value: float, prepared_100g: float, prepared_serving: float, prepared_unit: string>>
nutriscore_grade string
nutriscore_score int32
nutrition_data_per string
obsolete bool
origins_tags list<element: string>
origins string
owner_fields list<element: struct<field_name: string, timestamp: int64>>
owner string
packagings_complete bool
packaging_recycling_tags list<element: string>
packaging_shapes_tags list<element: string>
packaging_tags list<element: string>
packaging_text list<element: struct<lang: string, text: string>>
packaging string
packagings list<element: struct<material: string, number_of_units: int64, quantity_per_unit: string, quantity_per_unit_unit: string, quantity_per_unit_value: string, recycling: string, shape: string, weight_measured: float>>
photographers list<element: string>
popularity_key int64
popularity_tags list<element: string>
product_name list<element: struct<lang: string, text: string>>
product_quantity_unit string
product_quantity string
purchase_places_tags list<element: string>
quantity string
rev int32
scans_n int32
serving_quantity string
serving_size string
states_tags list<element: string>
stores_tags list<element: string>
stores string
traces_tags list<element: string>
unique_scans_n int32
unknown_ingredients_n int32
unknown_nutrients_tags list<element: string>
vitamins_tags list<element: string>
with_non_nutritive_sweeteners int32
with_sweeteners int32
schema_version int32

In [12]:
print('LOAD PARQUET FILE')
print()

check_duplicated = ["code"]

use_cols = check_duplicated + [
    "product_name", "brands",
    "lang",
    "nutriscore_score"
]

t.start()

df_parquet = pd.read_parquet(
    source_parquet,
    engine="pyarrow",
    columns=use_cols
)

display(df_parquet.info())

print(f"Dimensions : {df_parquet.shape}")
print(f"→ {df_parquet.shape[0]} lines, {df_parquet.shape[1]} columns\n")

t.end()

LOAD PARQUET FILE

<class 'pandas.DataFrame'>
RangeIndex: 4636471 entries, 0 to 4636470
Data columns (total 5 columns):
 #   Column            Dtype
---  ------            -----
 0   code              str
 1   product_name      object
 2   brands            str
 3   lang              str
 4   nutriscore_score  float64
dtypes: float64(1), object(1), str(3)
memory usage: 273.2+ MB

None

Dimensions : (4636471, 5)
→ 4636471 lines, 5 columns

Execution time : 10 seconds, 675 milliseconds and 596 microseconds
-----------------------

In [13]:
print('PARQUET SAMPLE DATA')

t.start()

with pd.option_context('display.max_colwidth', None):
    display(df_parquet.head(3))

t.end()

PARQUET SAMPLE DATA

,code,product_name,brands,lang,nutriscore_score
0,0000101209159,"[{'lang': 'main', 'text': 'Véritable pâte à tartiner noisettes chocolat noir'}, {'lang': 'fr', 'text': 'Véritable pâte à tartiner noisettes chocolat noir'}]",Bovetti,fr,25.0
1,0000105000011,"[{'lang': 'main', 'text': 'Chamomile Herbal Tea'}, {'lang': 'en', 'text': 'Chamomile Herbal Tea'}]",Lagg's,en,NaN
2,0000105000042,"[{'lang': 'main', 'text': 'Lagg's, herbal tea, peppermint'}, {'lang': 'en', 'text': 'Lagg's, herbal tea, peppermint'}]",Lagg's,en,NaN

Execution time : 13 milliseconds and 132 microseconds
-----------------------

In [14]:
t.start()

print(f"Duplication {check_duplicated}:")
print(df_parquet.duplicated(subset=check_duplicated).value_counts())
print()

print("Valeurs non-renseignées | Taux de remplissage par colonnes:")
missing = pd.DataFrame({
    'total_manquants': df_parquet.isna().sum(),
    '%': 100 - (df_parquet.isna().sum() / len(df_parquet) * 100).round(2)
})
print(missing)
print()

print("Produits vendu en France ([lang].eq(fr):)") #count
print(df_parquet[df_parquet["lang"].eq("fr")].shape[0])
print()

print("Top 10 marques: ")
print(df_parquet.groupby(["brands"]).size().sort_values(ascending=False)[0:10])
print()

print("Quelle part a un Nutri-Score renseigné ?")
print(f"Total: {df_parquet.shape[0]}")
print(f"Manquant: {df_parquet["nutriscore_score"].isna().sum()}")
print(f"Nutri-Score non-renseignés: {(df_parquet["nutriscore_score"].isna().sum() / len(df_full_csv) * 100).round(2)}%")

t.end()

Duplication ['code']:
False    4636411
True          60
Name: count, dtype: int64

Valeurs non-renseignées | Taux de remplissage par colonnes:
                  total_manquants       %
code                            0  100.00
product_name                    0  100.00
brands                    1595058   65.60
lang                            4  100.00
nutriscore_score          3255402   29.79

Produits vendu en France ([lang].eq(fr):)
1336912

Top 10 marques:
brands
             108709
Carrefour     20732
Coop          14545
Lidl          14243
U             12384
Aldi          12353
BonÀrea       12155
Hacendado     10658
Auchan        10590
Tesco         10503
dtype: int64

Quelle part a un Nutri-Score renseigné ?
Total: 4636471
Manquant: 3255402
Nutri-Score non-renseignés: 71.82%
Execution time : 2 seconds, 731 milliseconds and 75 microseconds
-----------------------